version: '3.9'

services:
  ml_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./mlruns:/app/mlruns
    environment:
      - PYTHONUNBUFFERED=1
    command: python train_docker.py
